### ISSUE TITLE
Overlapping Nodes

### ISSUE THREAD

**Issue by ronny1982** [jvloenen/OrgChart#3]
With some more sophisticated organizational layout, the nodes are overlapping. See attached demo source and screenshots...

[orgchart.html.txt](https://github.com/jvloenen/OrgChart/files/32620/orgchart.html.txt)

**Result:**
![error](https://cloud.githubusercontent.com/assets/4042685/11112209/037d8668-8911-11e5-8157-d7b22f92d391.png)
**Expected:**
![expected](https://cloud.githubusercontent.com/assets/4042685/11112210/03a69828-8911-11e5-94d9-902e1f8b465b.png)

**Comment by jvloenen** [comment]
Thanks for finding this bug. It is solved in version 1.12.
Your example now shows:

![ronny3](https://cloud.githubusercontent.com/assets/8167053/11332109/c32de1ce-91c2-11e5-895c-c32cd73b94f1.png)
